export const theme = {
	colors: {
		primary: '#d80520',
		primaryWithOpacity: 'rgba(216, 5, 32, 0.4)',
		secondary: '#31475b',
		accent: '#6063ff',
		error: '#9013fe',
		warning: '#6A451',
		white: '#ffffff',
		grey: '#999',
		black: '#000413',
		textPrimary: '#31475b',
		textSecondary: '#31475b',
		placeholderColor: '#999',
		textLinks: '#d80520',
		gradient: 'linear-gradient(to right, #ffdb3a 45%, #d80520 100%)',
		
	},

	button: {
		primary: {
			display: 'flex',
			justifyContent: 'center',
			width: 211,
			height: 32,
			alignSelf: 'center',
			alignItems: 'center',
			backgroundColor: '#153D8A',
			borderRadius: 10,
			marginTop: '5%',
		},
		secondary: {
			display: 'flex',
			justifyContent: 'center',
			width: 211,
			height: 32,
			alignSelf: 'center',
			alignItems: 'center',
			backgroundColor: '#9EC8F9',
			borderRadius: 10,
			marginTop: '5%',
		},
	},
	typography: {
		fontFamily: "-apple-system,BlinkMacSystemFont,\"Segoe UI\",Roboto,Oxygen-Sans,Ubuntu,Cantarell,\"Helvetica Neue\",sans-serif;",
		tinyFontSize: 8.5,
		miniFontSize: 12,
		smallFontSize: 14,
		mediumFontSize: 16,
		largeFontSize: 18,
		extraLargeFontSize: 22,
		fontWeightSemiBold: '600',
		fontWeightBold: '900',
	},
	spacing: {
		small: 4,
		medium: 8,
		large: 16,
	},
  sandBox: {
    colors: {
      surface1: "#ffffff",
      surface2: "#ebebeb",
      surface3: "#ffffff",
      clickable: "#31475b",
      base: "#31475b",
      disabled: "#d80520",
      hover: "#6063ff",
      accent: "#d80520",
      error: "#d80520",
      errorSurface: "#d80520"
    },
    syntax: {
      plain: "#000000",
      comment: {
        color: "#999",
        fontStyle: "italic",
      },
      keyword: "#6063ff",
      tag: "#d80520",
      punctuation: "#31475b",
      definition: "#d80520",
      property: "#6063ff",
      static: "#d80520",
      string: "#9013fe",
    },
    font: {
      body: "-apple-system,BlinkMacSystemFont,\"Segoe UI\",Roboto,Oxygen-Sans,Ubuntu,Cantarell,\"Helvetica Neue\",sans-serif;",
      mono: "-apple-system,BlinkMacSystemFont,\"Segoe UI\",Roboto,Oxygen-Sans,Ubuntu,Cantarell,\"Helvetica Neue\",sans-serif;",
      size: "16px",
      lineHeight: "22px",
    },
  }
}
