export const theme = {
	colors: {
		primary: '#153D8A',
		primaryWithOpacity: 'rgba(21, 61, 138, 0.4)',
		secondary: '#1C3E8C',
		accent: '#9EC8F9',
		error: '#E92C2C',
		warning: '#E19B00',
		white: '#ffffff',
		grey: '#707070',
		textPrimary: '#383737',
		textSecondary: '#1C3E8C',
		placeholderColor: '#B4B4B4',
		textLinks: '#326DC6',
	},

	button: {
		primary: {
			display: 'flex',
			justifyContent: 'center',
			width: 211,
			height: 32,
			alignSelf: 'center',
			alignItems: 'center',
			backgroundColor: '#153D8A',
			borderRadius: 10,
			marginTop: '5%',
		},
		secondary: {
			display: 'flex',
			justifyContent: 'center',
			width: 211,
			height: 32,
			alignSelf: 'center',
			alignItems: 'center',
			backgroundColor: '#9EC8F9',
			borderRadius: 10,
			marginTop: '5%',
		},
	},
	typography: {
		fontFamily: '',
		tinyFontSize: 8.5,
		miniFontSize: 12,
		smallFontSize: 14,
		mediumFontSize: 16,
		largeFontSize: 18,
		extraLargeFontSize: 22,
		fontWeightSemiBold: '600',
		fontWeightBold: '900',
	},
	spacing: {
		small: 4,
		medium: 8,
		large: 16,
	},
  sandBox: {
    colors: {
      surface1: "#ffffff",
      surface2: "#ebebeb",
      surface3: "#ffffff",
      clickable: "#31475b",
      base: "#ffffff",
      disabled: "#d80520",
      hover: "#6063ff",
      accent: "#d80520",
      error: "#d80520",
      errorSurface: "#d80520"
    },
    syntax: {
      plain: "#000000",
      comment: {
        color: "#999",
        fontStyle: "italic",
      },
      keyword: "#6063ff",
      tag: "#d80520",
      punctuation: "#31475b",
      definition: "#d80520",
      property: "#6063ff",
      static: "#d80520",
      string: "#9013fe",
    },
    font: {
      body: "-apple-system,BlinkMacSystemFont,\"Segoe UI\",Roboto,Oxygen-Sans,Ubuntu,Cantarell,\"Helvetica Neue\",sans-serif;",
      mono: "-apple-system,BlinkMacSystemFont,\"Segoe UI\",Roboto,Oxygen-Sans,Ubuntu,Cantarell,\"Helvetica Neue\",sans-serif;",
      size: "15px",
      lineHeight: "22px",
    },
  }
}
